# Generated by Django 5.2.3 on 2025-06-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('agente', 'Agente'), ('recepcionista', 'Recepcionista'), ('administrador', 'Administrador')], default='cliente', max_length=20),
        ),
    ]
