# Generated by Django 5.2.3 on 2025-07-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_options_alter_customuser_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('agente', 'Agente'), ('administrador', 'Administrador')], default='cliente', max_length=20),
        ),
    ]
