version: '3.8'

services:
  db:
    image: mariadb:11.3
    container_name: easytrip_mariadb
    restart: unless-stopped
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: easytrip123
      MYSQL_DATABASE: easytripdb
      MYSQL_USER: easytripuser
      MYSQL_PASSWORD: easytrip123
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - easytrip_net

  adminer:
    image: adminer
    container_name: easytrip_adminer
    restart: unless-stopped
    ports:
      - "8084:8080"
    networks:
      - easytrip_net

volumes:
  mariadb_data:

networks:
  easytrip_net:
    driver: bridge
