# Generated by Django 5.2.3 on 2025-06-13 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='paqueteturistico',
            table='paquete_turistico',
        ),
    ]
