# Generated by Django 5.2.3 on 2025-06-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigoverificacion',
            name='tipo',
            field=models.CharField(choices=[('registro', 'Registro'), ('recuperacion', 'Recuperación')], default='registro', max_length=20),
        ),
    ]
