# Generated by Django 5.2.3 on 2025-06-22 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0002_codigoverificacion_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenPaquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='paquetes/')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='tablas.paqueteturistico')),
            ],
            options={
                'db_table': 'imagenes_paquetes',
            },
        ),
    ]
