# Generated by Django 5.2.3 on 2025-06-14 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0003_reserva'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reserva',
            table='reserva',
        ),
    ]
