# Generated by Django 5.2.3 on 2025-06-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0004_alter_imagenpaquete_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenpaquete',
            name='es_predeterminada',
            field=models.BooleanField(default=False),
        ),
    ]
