# Generated by Django 5.2.3 on 2025-06-19 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0005_codigoverificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigoverificacion',
            name='fecha_expiracion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
