# Generated by Django 5.2.3 on 2025-06-27 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0005_imagenpaquete_es_predeterminada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenpaquete',
            name='es_predeterminada',
        ),
    ]
