# Generated by Django 5.2.3 on 2025-06-28 21:50

import tablas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0006_remove_es_predeterminada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenpaquete',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='paquetes/', validators=[tablas.models.validar_tamano_imagen]),
        ),
    ]
