# Generated by Django 5.2.3 on 2025-07-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0007_alter_imagenpaquete_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paqueteturistico',
            name='nombre',
            field=models.CharField(max_length=35),
        ),
    ]
