# Generated by Django 5.2.3 on 2025-08-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0008_alter_paqueteturistico_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paqueteturistico',
            name='descripcion',
            field=models.TextField(max_length=40),
        ),
        migrations.AlterField(
            model_name='paqueteturistico',
            name='nombre',
            field=models.CharField(max_length=25),
        ),
    ]
