# Generated by Django 5.2.3 on 2025-08-09 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0009_alter_paqueteturistico_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paqueteturistico',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
