# Generated by Django 5.2.3 on 2025-08-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0010_alter_paqueteturistico_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('pagada', 'Pagada'), ('cancelada', 'Cancelada'), ('finalizada', 'Finalizada')], default='pendiente', max_length=10),
        ),
    ]
